# Generated by Django 3.1.4 on 2021-09-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cidade',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.cidade'),
            preserve_default=False,
        ),
    ]
