# Generated by Django 3.1.4 on 2021-09-30 15:51

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210930_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cidade',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='main.cidade'),
            preserve_default=False,
        ),
    ]
