# Generated by Django 3.1.4 on 2021-10-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='conteudo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='Local',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='main.recipe'),
            preserve_default=False,
        ),
    ]
